apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: coit-frontend-listpods
subjects:
- kind: ServiceAccount
  name: coit-frontend 
  namespace: default # Name is case sensitive
roleRef:
  kind: ClusterRole
  name: list-pods
  apiGroup: rbac.authorization.k8s.io